# Extra autostart processes
# exec-once = uwsm-app -- my-service
# exec-once = uwsm-app -- /usr/lib/kdeconnectd

# Auto-resize Godot debug controls window
exec-once = ~/.config/hypr/scripts/godot-debug-resize.sh
