# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu


# Left monitor - 2560x1440 native
monitor=HDMI-A-1,2560x1440@144.01,0x0,1.00

# Center monitor - 4K scaled to 2560x1440 effective
monitor=DP-3,3840x2160@239.99,2560x0,1.50

# Right monitor - 2560x1440 native  
monitor=DP-1,2560x1440@165.00,5120x0,1.00

# misc {
#     mouse_move_enables_dpms = true
#     mouse_move_focuses_monitor = true
# }


# Persist workspaces on monitors
workspace = 1, monitor:DP-3
workspace = 2, monitor:DP-1
workspace = 3, monitor:HDMI-A-1
workspace = 4, monitor:HDMI-A-1, persistent:true
windowrulev2 = workspace 4 silent, class:^(Spotify)$
windowrulev2 = workspace 4 silent, class:^(discord)$
windowrulev2 = workspace 4 silent, class:^(pavucontrol)$
windowrulev2 = workspace 4 silent, class:^(btop)$
# Keep them from stealing focus
windowrulev2 = noinitialfocus, workspace:4

# games
windowrulev2 = noscale, class:^(steam_app_.*)$
windowrulev2 = noscale, class:^(gamescope)$
windowrulev2 = noscale, title:^(.*\.(exe|x86_64))$

windowrulev2 = monitor monitor:DP-3, class:^(steam_app_.*)$
windowrulev2 = monitor monitor:DP-3, class:^(gamescope)$
windowrulev2 = monitor monitor:DP-3, title:^(.*game.*)$